name: "Application Deployment Pipeline"

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy-app:
    uses: andrewhughes1988/platform-deployment-cicd/.github/workflows/terraform-pipeline.yml@main
    secrets: inherit
    with:
      environment: dev
      working_directory: "."
      var_file: environments/dev.tfvars
